name: CI workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello devs!
        run: echo "Hello! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"
        
      - name: More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Github Context: $GITHUB_CONTEXT"
          echo "Done!"
        

